name: C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install g++

    - name: Compile and run C++ code
      run: |
        g++ -o my_program ${{github.workspace}}/test.cpp
        ./${{github.workspace}}/my_program
        
    - name: Run the program
      run: ${{github.workspace}}/build
