name: C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install g++

    - name: Compile C++ code
      run: g++ -o /test/test.cpp

    - name: Run the program
      run: /home/gadji/exam/test.cpp
